### ISSUE TITLE
Remember current directory

### ISSUE THREAD

**Issue by andradei** [nimiq/promptastic#13]
Is Promptastic remembering the _current directory_ when a __new tab or window__ is opened? Or is it always putting the user on _home_?

**Comment by nimiq** [comment]
This is a feature related to the specific *terminal emulator*, not to *Promptastic*. The only thing *Promptastic* does is colouring the prompt; it can not access any info about other tabs and their current dir.

Talking about *terminal emulators*, I did some tests:
- *iTerm* and *Terminal* for Mac OS X does not support this feature;
- *GNOME Terminal* for Ubuntu does: say you have a terminal with current path to `/foo/bar` and you open a new tab, the new tab will be at `/foo/bar`

The good news is that *Promptastic* works well with all of them.

**Comment by nimiq** [comment]
Thanks to @andradei fix, the situation now is:
- *Terminal* for Mac OS X supports this feature: say the current directory in the active tab is `/foo/bar` and you open a new tab, then the new tab will be at `/foo/bar`;
- *iTerm* for Mac OS X does not support this feature;
- *GNOME Terminal* for Ubuntu does.
