### ISSUE TITLE
Executing install.py does nothing

### ISSUE THREAD

**Issue by Eriatolc** [nimiq/promptastic#21]
Hello there!

I was using your wonderful project on my previous Ubuntu, with Unity (yeah, everyone does some mistakes...). The installation was good.

I have re-installed my computer from scratch yesterday with a Kubuntu 15.04. So, I'm using Konsole now as terminal emulator. I wanted to re-install your project too, but when I am starting the `install.sh` file, it does nothing: no output.

I put the line `export TERM=xterm-256color` in my bashrc file as you mentioned in your INSTALL.md.

```
clotaire@Boromir:~$ echo $TERM
xterm-256color
```
Here is what it does when I start install.py file:
```
clotaire@Boromir:~$ cd Projets/promptastic/
clotaire@Boromir:~/Projets/promptastic$ ./install.py 
clotaire@Boromir:~/Projets/promptastic$ 
```
And then, Konsole is buggy, for example if I want to edit a file using vim in it after trying to install your project, it does this:

```
clotaire@Boromir:~/Projets/promptastic$ vim install.py 
Vim : Alerte : La sortie ne s'effectue pas sur un terminal (translation: Warning: output is not to a terminal)
```

Any help is appreciate! Thanks for your time.

**Comment by nimiq** [comment]
hmmmm... you can try to restart your computer and then run:
```
cd ~/Projets/promptastic
python install.py 
```
Let me know what happens.

**Comment by ldath** [comment]
This project is also not working in Lubuntu 14.04. I'm using Guake as a terminal. To reproduce just install Lubuntu 14.04 in Virtual Box.

**Comment by Eriatolc** [comment]
Ok, I have tried using python directly as you mentionned:
```
cd ~/Projets/promptastic
python install.py 
```

It worked like a charm! Have you an idea of why there is a difference?

Thanks again for your quick answer! It really helped! I close the issue.

**Comment by nimiq** [comment]
Yes, I'll fix that right now. Thanks for reporting!
