### ISSUE TITLE
Git showing "unknown" background

### ISSUE THREAD

**Issue by jetpacmonkey** [nimiq/promptastic#25]
I'm seeing this in all of my git repos:

![screen shot 2016-09-21 at 5 07 41 pm](https://cloud.githubusercontent.com/assets/1740479/18729036/09b800f8-801e-11e6-8f7e-4b7657799d74.png)

Not quite sure how to further debug this. It seems to have started happening after updating my version of xcode.

**Comment by jetpacmonkey** [comment]
It turns out I hadn't agreed to the Xcode license, so git integrations weren't working.

**Comment by Spaxe** [comment]
Can we have a note in the README about this? I got back to work today and had the same issue.
