### ISSUE TITLE
Why my prompt is so ugly?

### ISSUE THREAD

**Issue by tolerious** [nimiq/promptastic#7]
My prompt is like this:![Alt text](http://ww3.sinaimg.cn/mw690/a036a21agw1ele7ljkw4hj20ls07k408.jpg)

and yours:

![Alt text](https://cloud.githubusercontent.com/assets/6423485/4512433/51131d12-4b40-11e4-8ceb-cac7b01799da.png)

**Comment by sibljon** [comment]
For posterity: my prompt was missing the glyphs (as in OP's screenshot) and I fixed it via installing the powerline fonts:

```
# clone
git clone https://github.com/powerline/fonts.git
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts
```

Since I am using iTerm 2, I had to choose one of the Powerline fonts in iTerm's `Preferences > Profiles > Text`

Source: https://github.com/powerline/fonts
